# proxychains.conf  VER 4.x
#
#        HTTP, SOCKS4, SOCKS5 tunneling proxifier with DNS.

# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last one will be effective.
#
#dynamic_chain
strict_chain
#round_robin_chain
#random_chain

# Quiet mode (no output from library)
quiet_mode

# Proxy DNS requests - no leak for DNS data
proxy_dns 

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

# ProxyList format
#       type  host  port [user pass]
#       (values separated by 'tab' or 'blank')
#
[ProxyList]
# Default is Tor
# socks4 	127.0.0.1 9050

# User provided proxy
# IP: 195.96.136.148
# SOCKS5 Port: 18854
# User: user220034
# Pass: vt5g3j
socks5 127.0.0.1 1081
